version: "3"
services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - 127.0.0.1:9300:9300
      - 127.0.0.1:9200:9200
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    volumes:
      - ./data01:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - "ELASTICSEARCH_HOSTS=http://elastic:9200"
    depends_on:
      - elastic
